/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f9fbe7",
        "surface-dim": "#d9dcc8",
        "surface-bright": "#f9fbe7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f5e1",
        "surface-container": "#edf0dc",
        "surface-container-high": "#e8ead6",
        "surface-container-highest": "#e2e4d1",
        "on-surface": "#1a1d11",
        "on-surface-variant": "#41493e",
        "inverse-surface": "#2f3225",
        "inverse-on-surface": "#f0f2df",
        "outline": "#717a6d",
        "outline-variant": "#c0c9bb",
        "surface-tint": "#2a6b2c",
        "primary": "#00450d",
        "on-primary": "#ffffff",
        "primary-container": "#1b5e20",
        "on-primary-container": "#90d689",
        "inverse-primary": "#91d78a",
        "secondary": "#006e1c",
        "on-secondary": "#ffffff",
        "secondary-container": "#91f78e",
        "on-secondary-container": "#00731e",
        "tertiary": "#583100",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#794500",
        "on-tertiary-container": "#ffb66b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#acf4a4",
        "primary-fixed-dim": "#91d78a",
        "on-primary-fixed": "#002203",
        "on-primary-fixed-variant": "#0c5216",
        "secondary-fixed": "#94f990",
        "secondary-fixed-dim": "#78dc77",
        "on-secondary-fixed": "#002204",
        "on-secondary-fixed-variant": "#005313",
        "tertiary-fixed": "#ffdcbe",
        "tertiary-fixed-dim": "#ffb870",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-fixed-variant": "#693c00",
        "background": "#f9fbe7",
        "on-background": "#1a1d11",
        "surface-variant": "#e2e4d1",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "2.5rem",
        "stack-gap": "1rem",
        "touch-target-min": "56px",
        "margin-desktop": "4rem",
        "gutter": "1.5rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "label-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-xl": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg-mobile": ["Be Vietnam Pro", "sans-serif"],
        "headline-xl": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["18px", { lineHeight: "24px", letterSpacing: "0.5px", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "28px", fontWeight: "400" }],
        "body-xl": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }]
      },
      boxShadow: {
        "level-1": "0 4px 12px rgba(0, 0, 0, 0.08)",
        "level-2": "0 8px 24px rgba(255, 152, 0, 0.2)",
        "card": "0 4px 12px rgba(0, 0, 0, 0.1)",
        "mic": "0 4px 20px rgba(255, 152, 0, 0.25)"
      }
    },
  },
  plugins: [],
}
